version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: todoapp_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todoapp
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/1_init.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/2_seed.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci