-- MySQL Script generated by MySQL Workbench
-- Thu Jun 12 15:55:39 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `apellido` VARCHAR(100) NULL,
  `nick` VARCHAR(45) NOT NULL,
  `img_perfil` LONGBLOB NULL,
  `email` VARCHAR(255) NOT NULL,
  `contrasena` VARCHAR(255) NOT NULL,
  `primera_sesion` TINYINT(1) NULL DEFAULT 0,
  `fecha_creacion` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `borrado` TINYINT(1) NULL,
  `email_verificado` TINYINT(1) NULL,
  UNIQUE INDEX (`email` ASC) VISIBLE,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`familia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`familia` ;

CREATE TABLE IF NOT EXISTS `mydb`.`familia` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcion` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`ninos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ninos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ninos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `perfiles_aprendizaje_id` INT UNSIGNED NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `img_perfil` LONGBLOB NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `descripcion` TEXT NULL,
  `genero` VARCHAR(45) NULL,
  `peso` INT NULL,
  `altura` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ninos_perfiles_aprendizaje1_idx` (`perfiles_aprendizaje_id` ASC) VISIBLE,
  CONSTRAINT `fk_ninos_perfiles_aprendizaje1`
    FOREIGN KEY (`perfiles_aprendizaje_id`)
    REFERENCES `mydb`.`familia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`objetivos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`objetivos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`objetivos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `color` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `ninos_id` INT UNSIGNED NOT NULL,
  `fecha_fin` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_objetivos_ninos1_idx` (`ninos_id` ASC) VISIBLE,
  CONSTRAINT `fk_objetivos_ninos1`
    FOREIGN KEY (`ninos_id`)
    REFERENCES `mydb`.`ninos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`rutinas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`rutinas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`rutinas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ninos_id` INT UNSIGNED NOT NULL,
  `nombre` VARCHAR(100) NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `fecha_creacion` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `frecuencia` JSON NULL,
  `fecha_fin` DATE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_rutinas_ninos1_idx` (`ninos_id` ASC) VISIBLE,
  CONSTRAINT `fk_rutinas_ninos1`
    FOREIGN KEY (`ninos_id`)
    REFERENCES `mydb`.`ninos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`actividades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`actividades` ;

CREATE TABLE IF NOT EXISTS `mydb`.`actividades` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `rutina_id` INT UNSIGNED NOT NULL,
  `ninos_id` INT UNSIGNED NOT NULL,
  `titulo` VARCHAR(100) NULL DEFAULT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `dia_semana` TINYINT UNSIGNED NULL DEFAULT NULL,
  `hora_inicio` TIME NULL DEFAULT NULL,
  `hora_fin` TIME NULL DEFAULT NULL,
  `color` VARCHAR(45) NULL,
  `tipo` ENUM('Tarea', 'Evento', 'Habito') NULL,
  `ubicacion` JSON NULL,
  `usuario_responsable` INT NULL,
  `completado` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_actividad_rutina` (`rutina_id` ASC) VISIBLE,
  INDEX `fk_actividades_ninos1_idx` (`ninos_id` ASC) VISIBLE,
  CONSTRAINT `fk_actividad_rutina`
    FOREIGN KEY (`rutina_id`)
    REFERENCES `mydb`.`rutinas` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_actividades_ninos1`
    FOREIGN KEY (`ninos_id`)
    REFERENCES `mydb`.`ninos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`recordatorios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`recordatorios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`recordatorios` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `actividad_id` INT UNSIGNED NOT NULL,
  `fecha_envio` DATETIME NULL DEFAULT NULL,
  `enviado` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_recordatorio_actividad` (`actividad_id` ASC) VISIBLE,
  CONSTRAINT `fk_recordatorio_actividad`
    FOREIGN KEY (`actividad_id`)
    REFERENCES `mydb`.`actividades` (`id`)
    ON DELETE CASCADE);


-- -----------------------------------------------------
-- Table `mydb`.`sesiones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sesiones` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sesiones` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `usuario_id` INT UNSIGNED NOT NULL,
  `fecha_inicio` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_sesion_usuario` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_sesion_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE CASCADE);


-- -----------------------------------------------------
-- Table `mydb`.`alergias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`alergias` ;

CREATE TABLE IF NOT EXISTS `mydb`.`alergias` (
  `id` INT UNSIGNED NOT NULL,
  `ninos_id` INT UNSIGNED NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_alergias_ninos1_idx` (`ninos_id` ASC) VISIBLE,
  CONSTRAINT `fk_alergias_ninos1`
    FOREIGN KEY (`ninos_id`)
    REFERENCES `mydb`.`ninos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`notas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`notas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`notas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ninos_id` INT UNSIGNED NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `texto` TEXT NULL,
  `fecha_creacion` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_notas_ninos1_idx` (`ninos_id` ASC) VISIBLE,
  CONSTRAINT `fk_notas_ninos1`
    FOREIGN KEY (`ninos_id`)
    REFERENCES `mydb`.`ninos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`familia_usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`familia_usuarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`familia_usuarios` (
  `familia_id` INT UNSIGNED NOT NULL,
  `usuarios_id` INT UNSIGNED NOT NULL,
  `rol` ENUM('admin', 'cuidador', 'nino') NULL,
  PRIMARY KEY (`familia_id`, `usuarios_id`),
  INDEX `fk_perfiles_aprendizaje_has_usuarios_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  INDEX `fk_perfiles_aprendizaje_has_usuarios_perfiles_aprendizaje1_idx` (`familia_id` ASC) VISIBLE,
  CONSTRAINT `fk_perfiles_aprendizaje_has_usuarios_familia1`
    FOREIGN KEY (`familia_id`)
    REFERENCES `mydb`.`familia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_familia_has_usuarios_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`invitacion_usuario_familia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`invitacion_usuario_familia` ;

CREATE TABLE IF NOT EXISTS `mydb`.`invitacion_usuario_familia` (
  `id` INT UNSIGNED NOT NULL,
  `familia_id` INT UNSIGNED NOT NULL,
  `usuario_emisior` INT NULL,
  `email_destinatario` VARCHAR(45) NULL,
  `rol` ENUM('admin', 'cuidador', 'nino') NULL,
  `aceptado` TINYINT(1) NULL,
  `fecha_envio` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_invitacion_usuario_familia_familia1_idx` (`familia_id` ASC) VISIBLE,
  CONSTRAINT `fk_invitacion_usuario_familia_familia1`
    FOREIGN KEY (`familia_id`)
    REFERENCES `mydb`.`familia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`objetivos_has_actividades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`objetivos_has_actividades` ;

CREATE TABLE IF NOT EXISTS `mydb`.`objetivos_has_actividades` (
  `objetivos_id` INT UNSIGNED NOT NULL,
  `actividades_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`objetivos_id`, `actividades_id`),
  INDEX `fk_objetivos_has_actividades_actividades1_idx` (`actividades_id` ASC) VISIBLE,
  INDEX `fk_objetivos_has_actividades_objetivos1_idx` (`objetivos_id` ASC) VISIBLE,
  CONSTRAINT `fk_objetivos_has_actividades_objetivos1`
    FOREIGN KEY (`objetivos_id`)
    REFERENCES `mydb`.`objetivos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_objetivos_has_actividades_actividades1`
    FOREIGN KEY (`actividades_id`)
    REFERENCES `mydb`.`actividades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
